### ISSUE TITLE
Problema para gerar hash

### ISSUE THREAD

**Issue by JulioCRFilho** [kayque7k/Wirecard_gateway_for_flutter#3]
Não sei por quê motivo o hash não está sendo gerado quando utilizo o flutter build apk para distribuição de teste.
Qualquer forma que eu rode local, seja emulador ou device, e em qualquer modo (debug, profile, release), funciona normalmente. 
É só gerar o apk pra distribuição que o hash para de ser gerado, e eu já tentei de tudo que pude imaginar e que encontrei na internet e não descobri o motivo. Também não consegui debugar o erro porque só acontece com o apk gerado...
Existe alguma permissão que precise ser adicionada às plataformas nativas ou algo parecido?

**Comment by MateusMendesSantana** [comment]
Oi Júlio, creio que o algoritmo possa esta tendo problema por uma possível ofuscação do código. Possivelmente não esta relacionado com o problema, mas é melhor um palpite do que nada =): 
https://pub.dev/packages/fast_rsa#setup
https://www.thiengo.com.br/proguard-android

**Comment by JulioCRFilho** [comment]
Cara consegui resolver. O problema estava na segurança do Android que não permitia o `SpongyCastle` inicializar a criptografia, mesmo ela tendo sido adicionada no `Security.addProvider().` Então em ambiente de dev, mesmo rodando em modo release, debug ou profile, todos funcionavam, mas o APK gerado não tinha a mesma permissão do sistema Android igual o Android Studio tem.
Talvez eu esteja falando um absurdo completamente errado, mas foi o meu entendimento da situação, e resolvi esse problema removendo o provider "SC" da chamada `Cipher.getInstance("RSA/None/PKCS1Padding", "SC"),`.
